import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const REVIEWS = [
  { name: 'Zakarias Hartley', rating: 5, text: 'Beyond impressed and so happy with the work done by all at Harmonia. Everyone is so nice from the reception staff to the main man, Manuel. The endodontist performed root canal treatment to save a tooth which had a huge cavity.' },
  { name: 'Vikas Trivedi', rating: 5, text: 'The staff is very helpful and professional. Dr. Manuel has sharp eyes and makes insightful comments.' },
  { name: 'Angelo Moreno', rating: 5, text: 'Display is phenomenal absolutely excellent. I recommend for people to see the work they do, how professional these people are.' },
  { name: 'Taltunran', rating: 5, text: 'Here is the best dentist team I have had in my 37 years of life. Dr. Manuel and Dra. Cristina and Assistant Sandra took so good care of me I now would rather fly from Norway to this clinic than ever go to a dentist in Norway.' },
  { name: 'Diana Teys', rating: 5, text: 'A wonderful team. With my rather complex case, I arrived very scared, but thanks to Dr. Valero and his amazing team, they\'ve given me back my smile! At one point or another, I\'ve seen all the professionals, and each one has been excellent.' },
  { name: 'Al Varone', rating: 5, text: 'Great and innovative oral implant treatment. In 48 hours everything was out and all the implants were placed. No suffering. What they told me was 100% fulfilled. The attention and advice has been from true professionals, both in advance and after.' },
  { name: 'SARA VENTURA', rating: 5, text: 'A friend who lives nearby recommended them, and it was a great choice! This review is worth taking a few minutes to read — it\'s not only worthwhile to write reviews when something hasn\'t gone well.' },
  { name: 'Mario Albaladejo', rating: 5, text: 'I had implant surgery at Harmonia Dental Masnou, and all I can say is that it was spectacular. From day one, they made me feel at home, with a warm and very professional atmosphere.' },
  { name: 'Carla Carmona', rating: 5, text: 'Harmonia has always been my go-to clinic, thanks to the excellent service, the professionalism of the entire team, and the quality of their products. I highly recommend it if you\'re looking for quality and outstanding service.' },
  { name: 'Andrea Espinosa Llorente', rating: 5, text: 'I want to sincerely thank the team at Harmonia Dental. From the moment I met them, they\'ve made me feel comfortable, listened to, and at ease. It\'s clear they put dedication and care into their work, and that makes all the difference.' },
  { name: 'Oto Anguera Michelena', rating: 5, text: 'I had orthodontic treatment and I\'m very happy with the results. The customer service was exceptional, and the professionals are very friendly and do a great job. 100% recommended.' },
  { name: 'Jose', rating: 5, text: 'I had implants placed by Dr. Valero and his team at Harmonia Dental and was delighted with the results. Excellent treatment, very professional and attentive throughout. The procedure was quick, painless, and the results were perfect. Highly recommended!' },
  { name: 'CS Perruqueria', rating: 5, text: 'My case was truly complex, and I decided to undergo implant surgery under sedation, and it\'s changed my life. I can eat and, above all, smile without fear. Many thanks to the entire Harmonia team who have been supporting me and are very attentive.' },
  { name: 'Magalí Utrilla', rating: 5, text: 'I only have words of gratitude for the entire team! The attention and treatment from the beginning to the end of the treatment has always been a 10. My trusted dentists, 100% recommended!!!' },
  { name: 'Andreu Burguera', rating: 5, text: 'I\'m giving it 5 stars because there\'s no such thing as 6 or 7... Absolutely excellent! Great professionals, impeccable work, and unbeatable service. I\'m coming from Mallorca, and that says it all... THANK YOU, CRIS, CARME, MANU, and the entire staff. I\'m debuting a new smile today!' },
  { name: 'Josep Francesc Abril', rating: 5, text: 'They have always been very kind and attentive. Both for the cleanings and for the rest of the interventions, they have always been careful, and attentive to making me feel as comfortable as possible and minimizing any pain or discomfort.' },
  { name: 'Joana L.B.', rating: 5, text: 'Totally recommended. I had surgery with sedation for bone grafting and then for implants and everything was perfect, without pain or discomfort. Also treatment with Invisalign.' },
  { name: 'Roger Bascompte', rating: 5, text: 'I have been using Invisalign for half a year now and I am very happy. The treatment from the entire team is excellent, very friendly and attentive at all times. Highly recommended.' },
  { name: 'Araceli', rating: 5, text: 'Thanks to the entire team and especially to Dr. Valero and Dr. Bermúdez, as I really had a big problem with my mouth. I\'m a very nervous person but they handled it wonderfully.' },
  { name: 'Marco', rating: 5, text: 'I had several implants with Dr. Valero and it has truly been an excellent experience, accompanied by a very professional, attentive and very pleasant team at all times.' },
  { name: 'ASSOCIACIÓ ANIMALISTA SITGES ANGELS', rating: 5, text: 'Thanks to the whole team! Wonderful service and super professional. Highly recommended clinic with good prices.' },
  { name: 'Patricia Doñate', rating: 5, text: 'Great team of professionals. I always leave very happy. Unbeatable service and attention! Excellent work!' },
  { name: 'francesca', rating: 5, text: 'I\'ve always been very wary of going to the dentist, but this time is different, thanks to the entire team, with their excellent professionalism and friendly service!' },
  { name: 'klaudyee', rating: 5, text: 'I was terrified of going to the dentist, but since I met them, I\'m not afraid anymore. I\'ve had several treatments that usually hurt, and with them, I didn\'t notice a thing. They\'re also a super-friendly team and always treat you with a smile. Highly recommended!' },
  { name: 'daniel marquez', rating: 5, text: 'An unbeatable service, the hygienist Carme attended to me and did a very professional job. I recommend it 100%.' },
  { name: 'Alex Arellano Correas', rating: 5, text: 'Very professional and attentive, good treatment with patients, and very happy with my implant surgery and without pain, I recommend them!!' },
  { name: 'Anna B', rating: 5, text: 'Great professionals and excellent treatment. A few months ago, I had a night guard placed because I was grinding my teeth at night and waking up with discomfort and a headache. I went to their center, they recommended the guard, and I\'m very happy.' },
  { name: 'Nuria Fernandez Ferret', rating: 5, text: 'I had my orthodontic treatment with Invisalign and I\'m thrilled! They\'re a fantastic team! Thank you so much!' },
  { name: 'Valentí Canadell', rating: 5, text: 'Delighted with the service from the Harmonia Dental team. I recommend them 100%.' },
  { name: 'miquel aldana', rating: 5, text: 'From the first day everything has been perfect. I have two implants and no complications.' },
  { name: 'Jan Calomarde', rating: 5, text: 'Top experience. Always very friendly service, and it turned out great. 100% recommended.' },
  { name: 'Alfonso Delgado Mayolas', rating: 5, text: 'Excellent treatment, I have been treated for several procedures and very well, even with an implant performed.' },
  { name: 'rancisimo l', rating: 5, text: 'I started treatment with them. While the first impression was already positive, after starting treatment, I can confirm that they are truly professionals. All the staff I\'ve dealt with have been delightful. The facilities are modern.' },
  { name: 'Marta Lope', rating: 5, text: 'The best dental clinic, professionalism, friendliness, and the peace of mind of having a team of excellent professionals to whom you trust the care of your mouth. The whole family goes there and we\'re delighted.' },
  { name: 'Jessica Cabezas', rating: 5, text: 'Highly recommended!! They have a wonderful team. Kind, meticulous in their work, and a very professional and innovative group of young people. My experience with Doctors Manuel and Cristina was marvelous!!' },
  { name: 'María José Yubero', rating: 5, text: 'I just finished treatment with this great team and I couldn\'t be happier. Over the past few months, they reconstructed teeth, gave me two implants, and added a crown to a devitalized tooth. The results are incredible.' },
  { name: 'Agathe Dupont', rating: 5, text: 'Very attentive and caring staff. Excellent service and follow-up. I recommend it!' },
  { name: 'Caterina Medina', rating: 5, text: 'These are fantastic professionals; it was my first visit. They gave me excellent advice, my oral hygiene was done, and I\'ll definitely be back. The facilities are superb, as is all the equipment.' },
  { name: 'Marta Colom', rating: 5, text: 'I am very happy with the service. The staff is very friendly, attentive, professional and explains the entire process to follow clearly. The facilities are modern and clean. I totally recommend it!' },
  { name: 'catalina corcoles', rating: 5, text: 'From the reception to the doctor, all of them are great professionals and people. I have private insurance, but I chose them because they make you feel truly cared for.' },
  { name: 'marc ruiz', rating: 5, text: 'I recently visited the dental clinic and was completely impressed by the quality of service. From the moment I walked in, I felt welcomed and in professional hands. The clinic stands out for its impeccable cleanliness and comfortable atmosphere.' },
  { name: 'Daniel Marin', rating: 5, text: 'I\'ve had four sessions at Harmonia Clinic, and everything has been excellent. The staff\'s treatment has been impeccable, very professional and friendly. I\'m also very satisfied with the results and quality of the procedures. 100% recommended.' },
  { name: 'Sandra Fernandez Cornejo', rating: 5, text: 'I must say I thought my condition was hopeless... but I received the full explanation and the Invisalign treatment plan, with patience and follow-up care from both the doctors and the rest of the staff. I\'m very happy with the result.' },
  { name: 'Marc Fuster', rating: 5, text: '100% recommended. My whole family visits and we\'re delighted. Dr. Manuel is a great professional, as is the entire team. They\'re friendly and professional. From the moment you walk in the door, you\'re always warmly welcomed and given excellent advice.' },
  { name: 'carme rigat', rating: 5, text: 'Harmonia Dental is not only the best Dental Center I have ever known, but it is made up of a truly incredible team of people who make you feel comfortable and confident from the very beginning.' },
  { name: 'Charo Ortiz', rating: 5, text: 'They are fantastic, friendly, approachable, and super professional. I had a reconstruction problem years ago on an incisor overnight. The next day I called them and they reconstructed it the same day.' },
  { name: 'Joana B B', rating: 5, text: 'I congratulate the entire team at Harmonia Dental Masnou. We have been with them for 2 years now. The way they treat us gives you confidence and peace of mind. They present situations as they are and give you solutions to improve.' },
  { name: 'Natàlia Amorós', rating: 5, text: 'The entire team was super friendly and professional, my 1-year-old daughter left very happy.' },
  { name: 'Sonia bardaji bofill', rating: 5, text: 'My experience is fantastic, I say it from the bottom of my heart, the price, the professionalism, the kindness are a 10. The whole team is super. I was pleasantly surprised because my previous experiences with the dentist had been difficult.' },
  { name: 'Toni Cros', rating: 5, text: 'I was looking for a clinic close to home and followed the Google reviews. I was right on target! From day one, I received exquisite treatment from the entire team. I\'m now undergoing orthodontic treatment (Invisalign) and so far I\'m very happy.' },
  { name: 'Esther Ferret Sanchez', rating: 5, text: 'I\'ve had the opportunity to try Harmonia Dental and the experience has been truly wonderful. The staff is incredibly kind and professional, very attentive at all times. It\'s a calm, cool, and clean space.' },
  { name: 'xavier torra', rating: 5, text: 'They are very good professionals. I have been with dentists for many years and have had bad experiences and I am very happy to have found them. They were able to solve a rather complicated dental problem. They are also extraordinarily pleasant.' },
  { name: 'Laia Rúbies', rating: 5, text: 'The whole team is fantastic, both for adults and children! Always very pleasant and very professional treatment. I recommend it 100%!' },
  { name: 'Sali G G', rating: 5, text: 'Harmonia wins you over for their treatment and professionalism. I have a fear of dentists due to situations I have experienced in the past and also because of my oral sensitivity — but they handle it perfectly.' },
  { name: 'Angel Fernandez', rating: 5, text: 'The attention and service is great, I have been there several times and I recommend it whenever I can because my experience has always been positive, plus my son is happy and that says a lot.' },
  { name: 'Daniellie Hernández', rating: 5, text: 'For over three years, this has become my trusted dental center. I\'m currently completing my Invisalign treatment and am super happy with the results. I regularly get my dental hygiene done there. The team is spectacular.' },
  { name: 'Eva Martinez', rating: 5, text: 'We went to Harmonia Dental a year ago because it was recommended to us, as my son needed orthodontics. The Invisalign treatment and the excellent care we received from the wonderful team of professionals at this clinic have been a great success.' },
  { name: 'victor cuenca', rating: 5, text: 'I went to get a check-up and cleaning. After going to several dentists I wanted to find one close to home. They explained the treatment to me in great detail and without rushing. Very good treatment and very punctual.' },
  { name: 'Valentina Pogliano Cartro', rating: 5, text: 'Very happy with the treatment and the result.' },
  { name: 'Carlota Rodriguez Garcia', rating: 5, text: 'Very happy with Harmonía Dental. Great atmosphere and very professional staff. The best value for money I\'ve found in El Masnou.' },
  { name: 'marta pons canadell', rating: 5, text: 'They are very good professionals and at the same time they provide a personal and pleasant treatment. I have had several treatments there and they have always advised me very well, very attentive to how I was during the intervention. And the result is perfect!' },
  { name: 'Jordi Arpa', rating: 5, text: 'They are a very professional and friendly team who make you feel in good hands from the very first moment! And the quality-price ratio is unbeatable! 100% recommended! I\'ve been going for years and they never disappoint!' },
  { name: 'Estíbaliz FS', rating: 5, text: 'Highly recommended. I\'ve had several aesthetic treatments done and I\'ve been delighted with all the professionals who have treated me. I\'m especially grateful to Dr. Bermúdez. They were incredibly kind and efficient. I will definitely be back.' },
  { name: 'J.j. Vidal2061', rating: 5, text: 'I have just finished a very complete treatment, reconstructions, inlays and veneers. Months of work. Very happy with the attention and treatment received at all times. Very professional and I sincerely believe that despite being expensive it\'s worth it.' },
  { name: 'Susana Morales', rating: 5, text: 'Delighted with the care of the entire staff, from reception to departure. I feel extremely grateful for the consultation I received from Dr. Manuel Valero. Any dental service I need from now on, I will only want it at this dental center.' },
  { name: 'Ana Barea', rating: 5, text: 'I went a couple of years ago to get an orthodontic retainer, and the service and professionalism were outstanding. Today I visited the clinic again, and I couldn\'t be happier. The professionals are incredibly friendly and explain the entire treatment in detail.' },
  { name: 'Toni J', rating: 5, text: 'I went there for the first time on the advice of a friend, for a dental emergency, and I was pleasantly surprised. They are magnificent professionals, always attentive and with excellent treatment, almost familiar and very detailed.' },
  { name: 'Marta Padros', rating: 5, text: 'My experience at Harmonia Dental has been fantastic. Their team of professionals make you feel at home and their attention to people is unbeatable.' },
  { name: 'ANANDA SALUD NATURAL Natalia Abellaneda', rating: 5, text: 'I want to express my deep gratitude for the urgent care. Dr. Valero and his amazing team assessed me and operated on me immediately. I was blessed with the time I came to you.' },
  { name: 'David Blasco Julià', rating: 5, text: 'I\'ve never been a big fan of dentists, but the experience was excellent. My friend took me straight to Harmonia Dental after a fall, and I was very impressed.' },
  { name: 'mikel romo', rating: 5, text: 'Everything went very well. Dr. Valero and his entire team are excellent professionals who inspire a lot of confidence. The service is also fantastic; they are very friendly and attentive. I am very happy with the experience and the results.' },
  { name: 'Sofia Carballeira Perez', rating: 5, text: 'I\'m having Invisalign treatment with them and I couldn\'t be happier. They treat me wonderfully and the quality of their treatments is excellent.' },
  { name: 'Mundo Acuario', rating: 5, text: 'Very professional service. Always prioritizing the patient\'s comfort. 100% recommended. I had the pleasure of being treated by Mireia and it was fantastic.' },
  { name: 'Xavier Llopart', rating: 5, text: 'All the staff who work there are very good professionals and the human treatment is excellent. I had a tooth implant put in over a year ago and I am very satisfied with the result.' },
  { name: 'Joan Pages Zamora', rating: 5, text: 'The attention is very careful, good professionals and excellent treatment, very advisable and with a variety of schedules that facilitate the organization. Truly a dental clinic of the best.' },
  { name: 'Vicente Fernández Martínez', rating: 5, text: 'Great professionals, friendly and personal service. I\'m very happy with the result. They adapt to your schedule and make everything easy.' },
  { name: 'Manu', rating: 5, text: 'I\'ve been very happy from day one. The quality of the work is excellent, and they were attentive to every detail until everything was finished. They\'re a really great team.' },
  { name: 'Ismael López', rating: 5, text: 'The service I received from the first day I walked into Harmonía was excellent. The staff are highly professional and make you feel very comfortable at all times.' },
  { name: 'MEM', rating: 5, text: 'I just started my Invisalign orthodontic treatment at Harmonia and I couldn\'t be happier, both with the personal attention I\'m receiving from the doctor and the entire clinic team, and with their professionalism.' },
  { name: 'Esperanza Escola', rating: 5, text: 'Impeccable service, exquisite attention, they always treat us with familiarity and very good facilities.' },
  { name: 'David Castella', rating: 5, text: 'Dental clinic with the latest technologies and excellent professionals. They are very pleasant and attentive. They make you feel comfortable throughout the treatment.' },
  { name: 'J Miguel Gutierrez', rating: 5, text: 'Always delighted with the friendliness and professionalism of a fantastic team. 10 out of 10.' },
  { name: 'Manuel López', rating: 5, text: 'Professional team and personalized service. Very happy with the result. 100% recommended.' },
  { name: 'Sonia Arguisuelas', rating: 5, text: 'This clinic has excellent professionals who are very friendly and provide highly personalized service. I would definitely recommend it; they are always willing to help.' },
  { name: 'Natàlia Brenes Cordero', rating: 5, text: 'Super happy with the visit, with the treatment, the advice and the treatment we received from great professionals.' },
  { name: 'Loli Gp', rating: 5, text: 'I\'m so happy!! The staff are wonderful; you feel supported, listened to, and well-advised. They are also excellent professionals with great results. I highly recommend them!!' },
  { name: 'Carmen Varela Portela', rating: 5, text: 'A very good experience at Harmonia Dental Masnou. They are very professional, always attentive to the customer, and attentive to you with care and affection.' },
  { name: 'Grisel Boy', rating: 5, text: 'THANK YOU! To all the professionals who work at Harmonía Dental, you are wonderful. Excellence, respect and professionalism are what define this group of specialists.' },
  { name: 'Belén Aragón', rating: 5, text: 'Professionalism and kindness, two words that perfectly define this clinic. The treatment, explanations, and expertise of the entire team make everything very easy.' },
  { name: 'Mr Wolf', rating: 5, text: 'Very grateful for the treatment and service. Dr. Valero is a genius, Sandra is a delight, and Vanessa is very attentive. Great, and thank you! Also: incredible job with the cleaning.' },
  { name: 'Eva Díaz', rating: 5, text: 'I just finished my teeth whitening treatment with Dr. Zenaida and I couldn\'t be happier. Three years ago, I also had my orthodontics done with Harmonia Dental, and they left me with a dreamy smile. I\'m definitely in the best hands!' },
  { name: 'Carmen S.', rating: 5, text: 'It\'s been a year since I started my orthodontic treatment to reposition a tooth that was impacted in my palate. It\'s been super fast and not painful at all. I\'m very happy with the results and very grateful for the treatment and professionalism of the whole team!' },
  { name: 'Camille Rieunier', rating: 5, text: 'The Harmonia Dental team is very professional, and everyone is very attentive to their patients, always taking into account any potential phobias about going to the dentist.' },
  { name: 'Emma Estevez', rating: 5, text: 'I have a fear of dentists, and I was extremely happy with the treatment and kindness of Dr. Bermudez and her assistant, Maria. They are super professional, they make you feel comfortable, and you forget about your fear. 100% recommended.' },
  { name: 'Begoña Perez', rating: 5, text: 'I am very satisfied with Harmonía Dental. A center with advanced dental technology staffed by highly qualified professionals who advise you and provide the most appropriate solution for your problem. Very personalized service.' },
  { name: 'Nelly Cartró', rating: 5, text: 'Very happy with the service, professionalism, and the result.' },
  { name: 'Carla García / Carmen Ascó', rating: 5, text: 'I\'m delighted with the clinic. I\'m in the middle of treatment, and the procedure, staff, and space are all top-notch!' },
  { name: 'Guillem Ventura', rating: 5, text: 'I went to Harmonia Dental on the recommendation of a friend, and the treatment I received was excellent throughout. That\'s why they\'ve become my trusted dentist. I recommend them 100%.' },
  { name: 'Yippi jayhey', rating: 5, text: 'My case was quite dizzying... they had to extract about 20 teeth and then fit me with a prosthesis. At Harmonia Dental not only did they not judge me but they handled everything perfectly.' },
  { name: 'Victor Gayarre Blanco', rating: 5, text: 'A truly positive experience. I appreciate the service, the sincerity and professionalism of the entire team, the facilities, and of course, the quality of the final result. Excellent in every detail.' },
  { name: 'Jordi Lúñez Elena', rating: 5, text: 'EXCELLENT human and professional team.' },
  { name: 'Ester BG', rating: 5, text: 'I went because a bridge collapsed on me. They treated me extremely well, and the doctor explained everything to me in detail. The treatment and attention were 10/10.' },
  { name: 'Maite Perez', rating: 5, text: 'I\'m giving 5 stars because I can\'t give them more!!! They are charming and very professional. I\'m delighted with Harmonía Dental and their entire team.' },
  { name: 'Daniela J Pérez Campos', rating: 5, text: 'I went to have a gingivectomy and I really loved the result; also, Dr. Valero\'s treatment was excellent, as was that of the team itself.' },
  { name: 'Nancy Gissel Gonzalez Banegas', rating: 5, text: 'They are very professional and detailed with their work. I love it. I am super happy with the treatments they have performed on me.' },
  { name: 'Marti Noguer', rating: 5, text: 'A 10 in every way, my Doctor Cristina and her assistant Carme. I can\'t express how good they are, in every way.' },
  { name: 'Irma Lavall Torrents', rating: 5, text: 'As always, a very good experience. Unbeatable service, fluid communication, and excellent professionals. I\'m so glad I found you!' },
  { name: 'David Masso', rating: 5, text: 'Professional, efficient, empathetic, reasonably priced, and friendly. I highly recommend them.' },
  { name: 'Alex San Juan', rating: 5, text: 'Very happy and grateful. Excellent service. Professional, friendly, and attentive. Great cleanliness, organization, and hygiene. 100% recommended.' },
  { name: 'Alba Lavandero', rating: 5, text: 'They are charming, very professional, and know how to best meet your needs. I recommend them 100%.' },
  { name: 'Irene Lúñez Lope', rating: 5, text: 'A very close and professional treatment, especially from Sandra, the hygienist. The whole family goes there and we are very happy!' },
  { name: 'Romy Jurado cubero', rating: 5, text: 'They\'re incredibly professional, I\'m thrilled. They\'re nice and very friendly. I feel lucky to have found them.' },
  { name: 'Míriam Castells Lara', rating: 5, text: 'Professionalism, excellent follow-up and attention. Very happy.' },
  { name: 'Laura ibañez', rating: 5, text: 'Excellent service and attention! Good price and above all, the friendly treatment from the whole team who care about your well-being and your budget.' },
  { name: 'Xavi Delgado Carbi', rating: 5, text: 'Very happy, excellent service, and highly professional. I recommend 100%.' },
  { name: 'Nacho Lugo Camara', rating: 5, text: 'A team of excellent professionals. Just completed my orthodontic treatment, very satisfied with the treatment and the results.' },
  { name: 'Alex García', rating: 5, text: 'Excellent clinic. The staff is very professional and friendly. I will definitely return.' },
  { name: 'Jose Sanchez Fernadez', rating: 5, text: 'My trusted dental clinic. Thanks to them, my smile is much better. Expert and friendly team of specialists.' },
  { name: 'Javier Labrador', rating: 5, text: 'Excellent service, very professional, high-tech medical equipment, and punctual to the appointment time.' },
  { name: 'Ingrid López Solanas', rating: 5, text: 'I\'m thrilled with the result of my new smile! Everyone there is lovely and incredibly professional. I highly recommend them!' },
  { name: 'Rosa Maria Bosch i Tubau', rating: 5, text: 'Unbeatable clinic. Super good, friendly and very professional staff. The truth is that I am very happy!!!' },
  { name: 'Arantxa Gutierrez', rating: 5, text: 'Everything was great, great professionals! I was delighted with the result.' },
  { name: 'Anna Font Casanova', rating: 5, text: 'Excellent service! Friendly, pleasant and very professional.' },
  { name: 'Carolina Cayuela', rating: 5, text: 'Great professionals and very attentive. In addition, the facilities are beautiful, technologically advanced, and hygienic.' },
  { name: 'Jordi Moreno Rodriguez', rating: 5, text: 'My orthodontic treatment is over and I have a perfect smile! The service was incredible. Thank you so much to the entire Harmonía Dental team!' },
  { name: 'JMDR', rating: 5, text: 'Thanks to the entire Harmonia Dental team. Professionalism and kindness and a very good atmosphere. You are great!' },
  { name: 'Sonia Garcia diez', rating: 5, text: 'Grateful. I\'m no longer afraid. Polite, attentive, honest, and professional. Very happy.' },
  { name: 'Susana Morales', rating: 5, text: 'Delighted with the care of the entire staff. I feel extremely grateful for the consultation I received from Dr. Manuel Valero.' },
  { name: 'Marta Padros', rating: 5, text: 'My experience at Harmonia Dental has been fantastic. Their team of professionals make you feel at home and their attention to people is unbeatable.' },
  { name: 'Pilar Gimeno', rating: 5, text: 'Very satisfied with my implants and the treatment from the surgeon and team.' },
  // Negative reviews (kept for completeness, lower ratings)
  { name: 'Hug Marti', rating: 1, text: 'My wife has filed a complaint against this clinic, and the case is in progress. More than five years of suffering, and we\'re still stuck with this impressive botched job.' },
  { name: 'Hugo Martinez', rating: 1, text: 'My wife is suffering from all the shoddy work they\'ve done, and it\'s been going on for years. It\'s unbelievable, especially after having paid over €20,000.' },
  { name: 'Guido Castañeda', rating: 2, text: 'Unfortunately, I have to report a poor service experience. A crown on an implant which had come loose again. The follow-up fell short of expectations.' },
  { name: 'Constança Riu', rating: 1, text: 'My experience has been quite negative. They don\'t offer any explanations. I don\'t recommend it.' },
]

export async function POST() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: business } = await supabase
    .from('businesses')
    .select('id')
    .eq('user_id', user.id)
    .single()

  if (!business) return NextResponse.json({ error: 'No business found' }, { status: 404 })

  // Delete existing reviews
  await supabase.from('reviews').delete().eq('business_id', business.id)

  // Insert real reviews
  const rows = REVIEWS.map(r => ({
    business_id: business.id,
    customer_name: r.name,
    star_rating: r.rating,
    what_they_liked: r.text,
    staff_name: null,
    ai_draft: '',
    posted_to_google: true,
  }))

  const { error } = await supabase.from('reviews').insert(rows)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ success: true, count: rows.length })
}
